server:
  port: 8761



eureka:
  instance:
    hostname: localhost
  client:
    # register-with-eureka和fetch-registry false表明自己是一个server
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/