eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8762

spring:
  application:
    name: service-demo
  datasource:
    url: jdbc:mysql://server-proxy.aimingtai.com:3306/cmsdb?characterEncoding=UTF-8
    username: cmsadmin
    password: cmsadmin123

mybatis:
  config-location: classpath:mybitas-config.xml

